# Generated by Django 3.1.5 on 2021-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('q1', models.BooleanField(default=False)),
                ('q2', models.BooleanField(default=False)),
                ('q3', models.BooleanField(default=False)),
                ('q4', models.BooleanField(default=False)),
                ('q5', models.BooleanField(default=False)),
                ('q6', models.BooleanField(default=False)),
                ('q7', models.BooleanField(default=False)),
            ],
        ),
    ]
